apiVersion: servicecatalog.aws.upbound.io/v1beta1
kind: ProvisionedProduct
metadata:
  annotations:
    meta.upbound.io/example-id: servicecatalog/v1beta1/provisionedproduct
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: example
    productName: Example product
    provisioningArtifactName: Example version
    provisioningParameters:
    - key: foo
      value: bar
    region: us-west-1
    tags:
      foo: bar

---

